export const Countries = [
  {
    numCode: '4',
    shortCode: 'AF',
    fullCode: 'AFG',
    name: 'Afghanistan',
    nationality: 'Afghan',
  },
  {
    numCode: '248',
    shortCode: 'AX',
    fullCode: 'ALA',
    name: '\u00c5land Islands',
    nationality: '\u00c5land Island',
  },
  {
    numCode: '8',
    shortCode: 'AL',
    fullCode: 'ALB',
    name: 'Albania',
    nationality: 'Albanian',
  },
  {
    numCode: '12',
    shortCode: 'DZ',
    fullCode: 'DZA',
    name: 'Algeria',
    nationality: 'Algerian',
  },
  {
    numCode: '16',
    shortCode: 'AS',
    fullCode: 'ASM',
    name: 'American Samoa',
    nationality: 'American Samoan',
  },
  {
    numCode: '20',
    shortCode: 'AD',
    fullCode: 'AND',
    name: 'Andorra',
    nationality: 'Andorran',
  },
  {
    numCode: '24',
    shortCode: 'AO',
    fullCode: 'AGO',
    name: 'Angola',
    nationality: 'Angolan',
  },
  {
    numCode: '660',
    shortCode: 'AI',
    fullCode: 'AIA',
    name: 'Anguilla',
    nationality: 'Anguillan',
  },
  {
    numCode: '10',
    shortCode: 'AQ',
    fullCode: 'ATA',
    name: 'Antarctica',
    nationality: 'Antarctic',
  },
  {
    numCode: '28',
    shortCode: 'AG',
    fullCode: 'ATG',
    name: 'Antigua and Barbuda',
    nationality: 'Antiguan or Barbudan',
  },
  {
    numCode: '32',
    shortCode: 'AR',
    fullCode: 'ARG',
    name: 'Argentina',
    nationality: 'Argentine',
  },
  {
    numCode: '51',
    shortCode: 'AM',
    fullCode: 'ARM',
    name: 'Armenia',
    nationality: 'Armenian',
  },
  {
    numCode: '533',
    shortCode: 'AW',
    fullCode: 'ABW',
    name: 'Aruba',
    nationality: 'Aruban',
  },
  {
    numCode: '36',
    shortCode: 'AU',
    fullCode: 'AUS',
    name: 'Australia',
    nationality: 'Australian',
  },
  {
    numCode: '40',
    shortCode: 'AT',
    fullCode: 'AUT',
    name: 'Austria',
    nationality: 'Austrian',
  },
  {
    numCode: '31',
    shortCode: 'AZ',
    fullCode: 'AZE',
    name: 'Azerbaijan',
    nationality: 'Azerbaijani, Azeri',
  },
  {
    numCode: '44',
    shortCode: 'BS',
    fullCode: 'BHS',
    name: 'Bahamas',
    nationality: 'Bahamian',
  },
  {
    numCode: '48',
    shortCode: 'BH',
    fullCode: 'BHR',
    name: 'Bahrain',
    nationality: 'Bahraini',
  },
  {
    numCode: '50',
    shortCode: 'BD',
    fullCode: 'BGD',
    name: 'Bangladesh',
    nationality: 'Bangladeshi',
  },
  {
    numCode: '52',
    shortCode: 'BB',
    fullCode: 'BRB',
    name: 'Barbados',
    nationality: 'Barbadian',
  },
  {
    numCode: '112',
    shortCode: 'BY',
    fullCode: 'BLR',
    name: 'Belarus',
    nationality: 'Belarusian',
  },
  {
    numCode: '56',
    shortCode: 'BE',
    fullCode: 'BEL',
    name: 'Belgium',
    nationality: 'Belgian',
  },
  {
    numCode: '84',
    shortCode: 'BZ',
    fullCode: 'BLZ',
    name: 'Belize',
    nationality: 'Belizean',
  },
  {
    numCode: '204',
    shortCode: 'BJ',
    fullCode: 'BEN',
    name: 'Benin',
    nationality: 'Beninese, Beninois',
  },
  {
    numCode: '60',
    shortCode: 'BM',
    fullCode: 'BMU',
    name: 'Bermuda',
    nationality: 'Bermudian, Bermudan',
  },
  {
    numCode: '64',
    shortCode: 'BT',
    fullCode: 'BTN',
    name: 'Bhutan',
    nationality: 'Bhutanese',
  },
  {
    numCode: '68',
    shortCode: 'BO',
    fullCode: 'BOL',
    name: 'Bolivia (Plurinational State of)',
    nationality: 'Bolivian',
  },
  {
    numCode: '535',
    shortCode: 'BQ',
    fullCode: 'BES',
    name: 'Bonaire, Sint Eustatius and Saba',
    nationality: 'Bonaire',
  },
  {
    numCode: '70',
    shortCode: 'BA',
    fullCode: 'BIH',
    name: 'Bosnia and Herzegovina',
    nationality: 'Bosnian or Herzegovinian',
  },
  {
    numCode: '72',
    shortCode: 'BW',
    fullCode: 'BWA',
    name: 'Botswana',
    nationality: 'Motswana, Botswanan',
  },
  {
    numCode: '74',
    shortCode: 'BV',
    fullCode: 'BVT',
    name: 'Bouvet Island',
    nationality: 'Bouvet Island',
  },
  {
    numCode: '76',
    shortCode: 'BR',
    fullCode: 'BRA',
    name: 'Brazil',
    nationality: 'Brazilian',
  },
  {
    numCode: '86',
    shortCode: 'IO',
    fullCode: 'IOT',
    name: 'British Indian Ocean Territory',
    nationality: 'BIOT',
  },
  {
    numCode: '96',
    shortCode: 'BN',
    fullCode: 'BRN',
    name: 'Brunei Darussalam',
    nationality: 'Bruneian',
  },
  {
    numCode: '100',
    shortCode: 'BG',
    fullCode: 'BGR',
    name: 'Bulgaria',
    nationality: 'Bulgarian',
  },
  {
    numCode: '854',
    shortCode: 'BF',
    fullCode: 'BFA',
    name: 'Burkina Faso',
    nationality: 'Burkinab\u00e9',
  },
  {
    numCode: '108',
    shortCode: 'BI',
    fullCode: 'BDI',
    name: 'Burundi',
    nationality: 'Burundian',
  },
  {
    numCode: '132',
    shortCode: 'CV',
    fullCode: 'CPV',
    name: 'Cabo Verde',
    nationality: 'Cabo Verdean',
  },
  {
    numCode: '116',
    shortCode: 'KH',
    fullCode: 'KHM',
    name: 'Cambodia',
    nationality: 'Cambodian',
  },
  {
    numCode: '120',
    shortCode: 'CM',
    fullCode: 'CMR',
    name: 'Cameroon',
    nationality: 'Cameroonian',
  },
  {
    numCode: '124',
    shortCode: 'CA',
    fullCode: 'CAN',
    name: 'Canada',
    nationality: 'Canadian',
  },
  {
    numCode: '136',
    shortCode: 'KY',
    fullCode: 'CYM',
    name: 'Cayman Islands',
    nationality: 'Caymanian',
  },
  {
    numCode: '140',
    shortCode: 'CF',
    fullCode: 'CAF',
    name: 'Central African Republic',
    nationality: 'Central African',
  },
  {
    numCode: '148',
    shortCode: 'TD',
    fullCode: 'TCD',
    name: 'Chad',
    nationality: 'Chadian',
  },
  {
    numCode: '152',
    shortCode: 'CL',
    fullCode: 'CHL',
    name: 'Chile',
    nationality: 'Chilean',
  },
  {
    numCode: '156',
    shortCode: 'CN',
    fullCode: 'CHN',
    name: 'China',
    nationality: 'Chinese',
  },
  {
    numCode: '162',
    shortCode: 'CX',
    fullCode: 'CXR',
    name: 'Christmas Island',
    nationality: 'Christmas Island',
  },
  {
    numCode: '166',
    shortCode: 'CC',
    fullCode: 'CCK',
    name: 'Cocos (Keeling) Islands',
    nationality: 'Cocos Island',
  },
  {
    numCode: '170',
    shortCode: 'CO',
    fullCode: 'COL',
    name: 'Colombia',
    nationality: 'Colombian',
  },
  {
    numCode: '174',
    shortCode: 'KM',
    fullCode: 'COM',
    name: 'Comoros',
    nationality: 'Comoran, Comorian',
  },
  {
    numCode: '178',
    shortCode: 'CG',
    fullCode: 'COG',
    name: 'Congo (Republic of the)',
    nationality: 'Congolese',
  },
  {
    numCode: '180',
    shortCode: 'CD',
    fullCode: 'COD',
    name: 'Congo (Democratic Republic of the)',
    nationality: 'Congolese',
  },
  {
    numCode: '184',
    shortCode: 'CK',
    fullCode: 'COK',
    name: 'Cook Islands',
    nationality: 'Cook Island',
  },
  {
    numCode: '188',
    shortCode: 'CR',
    fullCode: 'CRI',
    name: 'Costa Rica',
    nationality: 'Costa Rican',
  },
  {
    numCode: '384',
    shortCode: 'CI',
    fullCode: 'CIV',
    name: "C\u00f4te d'Ivoire",
    nationality: 'Ivorian',
  },
  {
    numCode: '191',
    shortCode: 'HR',
    fullCode: 'HRV',
    name: 'Croatia',
    nationality: 'Croatian',
  },
  {
    numCode: '192',
    shortCode: 'CU',
    fullCode: 'CUB',
    name: 'Cuba',
    nationality: 'Cuban',
  },
  {
    numCode: '531',
    shortCode: 'CW',
    fullCode: 'CUW',
    name: 'Cura\u00e7ao',
    nationality: 'Cura\u00e7aoan',
  },
  {
    numCode: '196',
    shortCode: 'CY',
    fullCode: 'CYP',
    name: 'Cyprus',
    nationality: 'Cypriot',
  },
  {
    numCode: '203',
    shortCode: 'CZ',
    fullCode: 'CZE',
    name: 'Czech Republic',
    nationality: 'Czech',
  },
  {
    numCode: '208',
    shortCode: 'DK',
    fullCode: 'DNK',
    name: 'Denmark',
    nationality: 'Danish',
  },
  {
    numCode: '262',
    shortCode: 'DJ',
    fullCode: 'DJI',
    name: 'Djibouti',
    nationality: 'Djiboutian',
  },
  {
    numCode: '212',
    shortCode: 'DM',
    fullCode: 'DMA',
    name: 'Dominica',
    nationality: 'Dominican',
  },
  {
    numCode: '214',
    shortCode: 'DO',
    fullCode: 'DOM',
    name: 'Dominican Republic',
    nationality: 'Dominican',
  },
  {
    numCode: '218',
    shortCode: 'EC',
    fullCode: 'ECU',
    name: 'Ecuador',
    nationality: 'Ecuadorian',
  },
  {
    numCode: '818',
    shortCode: 'EG',
    fullCode: 'EGY',
    name: 'Egypt',
    nationality: 'Egyptian',
  },
  {
    numCode: '222',
    shortCode: 'SV',
    fullCode: 'SLV',
    name: 'El Salvador',
    nationality: 'Salvadoran',
  },
  {
    numCode: '226',
    shortCode: 'GQ',
    fullCode: 'GNQ',
    name: 'Equatorial Guinea',
    nationality: 'Equatorial Guinean, Equatoguinean',
  },
  {
    numCode: '232',
    shortCode: 'ER',
    fullCode: 'ERI',
    name: 'Eritrea',
    nationality: 'Eritrean',
  },
  {
    numCode: '233',
    shortCode: 'EE',
    fullCode: 'EST',
    name: 'Estonia',
    nationality: 'Estonian',
  },
  {
    numCode: '231',
    shortCode: 'ET',
    fullCode: 'ETH',
    name: 'Ethiopia',
    nationality: 'Ethiopian',
  },
  {
    numCode: '238',
    shortCode: 'FK',
    fullCode: 'FLK',
    name: 'Falkland Islands (Malvinas)',
    nationality: 'Falkland Island',
  },
  {
    numCode: '234',
    shortCode: 'FO',
    fullCode: 'FRO',
    name: 'Faroe Islands',
    nationality: 'Faroese',
  },
  {
    numCode: '242',
    shortCode: 'FJ',
    fullCode: 'FJI',
    name: 'Fiji',
    nationality: 'Fijian',
  },
  {
    numCode: '246',
    shortCode: 'FI',
    fullCode: 'FIN',
    name: 'Finland',
    nationality: 'Finnish',
  },
  {
    numCode: '250',
    shortCode: 'FR',
    fullCode: 'FRA',
    name: 'France',
    nationality: 'French',
  },
  {
    numCode: '254',
    shortCode: 'GF',
    fullCode: 'GUF',
    name: 'French Guiana',
    nationality: 'French Guianese',
  },
  {
    numCode: '258',
    shortCode: 'PF',
    fullCode: 'PYF',
    name: 'French Polynesia',
    nationality: 'French Polynesian',
  },
  {
    numCode: '260',
    shortCode: 'TF',
    fullCode: 'ATF',
    name: 'French Southern Territories',
    nationality: 'French Southern Territories',
  },
  {
    numCode: '266',
    shortCode: 'GA',
    fullCode: 'GAB',
    name: 'Gabon',
    nationality: 'Gabonese',
  },
  {
    numCode: '270',
    shortCode: 'GM',
    fullCode: 'GMB',
    name: 'Gambia',
    nationality: 'Gambian',
  },
  {
    numCode: '268',
    shortCode: 'GE',
    fullCode: 'GEO',
    name: 'Georgia',
    nationality: 'Georgian',
  },
  {
    numCode: '276',
    shortCode: 'DE',
    fullCode: 'DEU',
    name: 'Germany',
    nationality: 'German',
  },
  {
    numCode: '288',
    shortCode: 'GH',
    fullCode: 'GHA',
    name: 'Ghana',
    nationality: 'Ghanaian',
  },
  {
    numCode: '292',
    shortCode: 'GI',
    fullCode: 'GIB',
    name: 'Gibraltar',
    nationality: 'Gibraltar',
  },
  {
    numCode: '300',
    shortCode: 'GR',
    fullCode: 'GRC',
    name: 'Greece',
    nationality: 'Greek, Hellenic',
  },
  {
    numCode: '304',
    shortCode: 'GL',
    fullCode: 'GRL',
    name: 'Greenland',
    nationality: 'Greenlandic',
  },
  {
    numCode: '308',
    shortCode: 'GD',
    fullCode: 'GRD',
    name: 'Grenada',
    nationality: 'Grenadian',
  },
  {
    numCode: '312',
    shortCode: 'GP',
    fullCode: 'GLP',
    name: 'Guadeloupe',
    nationality: 'Guadeloupe',
  },
  {
    numCode: '316',
    shortCode: 'GU',
    fullCode: 'GUM',
    name: 'Guam',
    nationality: 'Guamanian, Guambat',
  },
  {
    numCode: '320',
    shortCode: 'GT',
    fullCode: 'GTM',
    name: 'Guatemala',
    nationality: 'Guatemalan',
  },
  {
    numCode: '831',
    shortCode: 'GG',
    fullCode: 'GGY',
    name: 'Guernsey',
    nationality: 'Channel Island',
  },
  {
    numCode: '324',
    shortCode: 'GN',
    fullCode: 'GIN',
    name: 'Guinea',
    nationality: 'Guinean',
  },
  {
    numCode: '624',
    shortCode: 'GW',
    fullCode: 'GNB',
    name: 'Guinea-Bissau',
    nationality: 'Bissau-Guinean',
  },
  {
    numCode: '328',
    shortCode: 'GY',
    fullCode: 'GUY',
    name: 'Guyana',
    nationality: 'Guyanese',
  },
  {
    numCode: '332',
    shortCode: 'HT',
    fullCode: 'HTI',
    name: 'Haiti',
    nationality: 'Haitian',
  },
  {
    numCode: '334',
    shortCode: 'HM',
    fullCode: 'HMD',
    name: 'Heard Island and McDonald Islands',
    nationality: 'Heard Island or McDonald Islands',
  },
  {
    numCode: '336',
    shortCode: 'VA',
    fullCode: 'VAT',
    name: 'Vatican City State',
    nationality: 'Vatican',
  },
  {
    numCode: '340',
    shortCode: 'HN',
    fullCode: 'HND',
    name: 'Honduras',
    nationality: 'Honduran',
  },
  {
    numCode: '344',
    shortCode: 'HK',
    fullCode: 'HKG',
    name: 'Hong Kong',
    nationality: 'Hong Kong, Hong Kongese',
  },
  {
    numCode: '348',
    shortCode: 'HU',
    fullCode: 'HUN',
    name: 'Hungary',
    nationality: 'Hungarian, Magyar',
  },
  {
    numCode: '352',
    shortCode: 'IS',
    fullCode: 'ISL',
    name: 'Iceland',
    nationality: 'Icelandic',
  },
  {
    numCode: '356',
    shortCode: 'IN',
    fullCode: 'IND',
    name: 'India',
    nationality: 'Indian',
  },
  {
    numCode: '360',
    shortCode: 'ID',
    fullCode: 'IDN',
    name: 'Indonesia',
    nationality: 'Indonesian',
  },
  {
    numCode: '364',
    shortCode: 'IR',
    fullCode: 'IRN',
    name: 'Iran',
    nationality: 'Iranian, Persian',
  },
  {
    numCode: '368',
    shortCode: 'IQ',
    fullCode: 'IRQ',
    name: 'Iraq',
    nationality: 'Iraqi',
  },
  {
    numCode: '372',
    shortCode: 'IE',
    fullCode: 'IRL',
    name: 'Ireland',
    nationality: 'Irish',
  },
  {
    numCode: '833',
    shortCode: 'IM',
    fullCode: 'IMN',
    name: 'Isle of Man',
    nationality: 'Manx',
  },
  {
    numCode: '376',
    shortCode: 'IL',
    fullCode: 'ISR',
    name: 'Israel',
    nationality: 'Israeli',
  },
  {
    numCode: '380',
    shortCode: 'IT',
    fullCode: 'ITA',
    name: 'Italy',
    nationality: 'Italian',
  },
  {
    numCode: '388',
    shortCode: 'JM',
    fullCode: 'JAM',
    name: 'Jamaica',
    nationality: 'Jamaican',
  },
  {
    numCode: '392',
    shortCode: 'JP',
    fullCode: 'JPN',
    name: 'Japan',
    nationality: 'Japanese',
  },
  {
    numCode: '832',
    shortCode: 'JE',
    fullCode: 'JEY',
    name: 'Jersey',
    nationality: 'Channel Island',
  },
  {
    numCode: '400',
    shortCode: 'JO',
    fullCode: 'JOR',
    name: 'Jordan',
    nationality: 'Jordanian',
  },
  {
    numCode: '398',
    shortCode: 'KZ',
    fullCode: 'KAZ',
    name: 'Kazakhstan',
    nationality: 'Kazakhstani, Kazakh',
  },
  {
    numCode: '404',
    shortCode: 'KE',
    fullCode: 'KEN',
    name: 'Kenya',
    nationality: 'Kenyan',
  },
  {
    numCode: '296',
    shortCode: 'KI',
    fullCode: 'KIR',
    name: 'Kiribati',
    nationality: 'I-Kiribati',
  },
  {
    numCode: '408',
    shortCode: 'KP',
    fullCode: 'PRK',
    name: "Korea (Democratic People's Republic of)",
    nationality: 'North Korean',
  },
  {
    numCode: '410',
    shortCode: 'KR',
    fullCode: 'KOR',
    name: 'Korea (Republic of)',
    nationality: 'South Korean',
  },
  {
    numCode: '414',
    shortCode: 'KW',
    fullCode: 'KWT',
    name: 'Kuwait',
    nationality: 'Kuwaiti',
  },
  {
    numCode: '417',
    shortCode: 'KG',
    fullCode: 'KGZ',
    name: 'Kyrgyzstan',
    nationality: 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz',
  },
  {
    numCode: '418',
    shortCode: 'LA',
    fullCode: 'LAO',
    name: "Lao People's Democratic Republic",
    nationality: 'Lao, Laotian',
  },
  {
    numCode: '428',
    shortCode: 'LV',
    fullCode: 'LVA',
    name: 'Latvia',
    nationality: 'Latvian',
  },
  {
    numCode: '422',
    shortCode: 'LB',
    fullCode: 'LBN',
    name: 'Lebanon',
    nationality: 'Lebanese',
  },
  {
    numCode: '426',
    shortCode: 'LS',
    fullCode: 'LSO',
    name: 'Lesotho',
    nationality: 'Basotho',
  },
  {
    numCode: '430',
    shortCode: 'LR',
    fullCode: 'LBR',
    name: 'Liberia',
    nationality: 'Liberian',
  },
  {
    numCode: '434',
    shortCode: 'LY',
    fullCode: 'LBY',
    name: 'Libya',
    nationality: 'Libyan',
  },
  {
    numCode: '438',
    shortCode: 'LI',
    fullCode: 'LIE',
    name: 'Liechtenstein',
    nationality: 'Liechtenstein',
  },
  {
    numCode: '440',
    shortCode: 'LT',
    fullCode: 'LTU',
    name: 'Lithuania',
    nationality: 'Lithuanian',
  },
  {
    numCode: '442',
    shortCode: 'LU',
    fullCode: 'LUX',
    name: 'Luxembourg',
    nationality: 'Luxembourg, Luxembourgish',
  },
  {
    numCode: '446',
    shortCode: 'MO',
    fullCode: 'MAC',
    name: 'Macao',
    nationality: 'Macanese, Chinese',
  },
  {
    numCode: '807',
    shortCode: 'MK',
    fullCode: 'MKD',
    name: 'Macedonia (the former Yugoslav Republic of)',
    nationality: 'Macedonian',
  },
  {
    numCode: '450',
    shortCode: 'MG',
    fullCode: 'MDG',
    name: 'Madagascar',
    nationality: 'Malagasy',
  },
  {
    numCode: '454',
    shortCode: 'MW',
    fullCode: 'MWI',
    name: 'Malawi',
    nationality: 'Malawian',
  },
  {
    numCode: '458',
    shortCode: 'MY',
    fullCode: 'MYS',
    name: 'Malaysia',
    nationality: 'Malaysian',
  },
  {
    numCode: '462',
    shortCode: 'MV',
    fullCode: 'MDV',
    name: 'Maldives',
    nationality: 'Maldivian',
  },
  {
    numCode: '466',
    shortCode: 'ML',
    fullCode: 'MLI',
    name: 'Mali',
    nationality: 'Malian, Malinese',
  },
  {
    numCode: '470',
    shortCode: 'MT',
    fullCode: 'MLT',
    name: 'Malta',
    nationality: 'Maltese',
  },
  {
    numCode: '584',
    shortCode: 'MH',
    fullCode: 'MHL',
    name: 'Marshall Islands',
    nationality: 'Marshallese',
  },
  {
    numCode: '474',
    shortCode: 'MQ',
    fullCode: 'MTQ',
    name: 'Martinique',
    nationality: 'Martiniquais, Martinican',
  },
  {
    numCode: '478',
    shortCode: 'MR',
    fullCode: 'MRT',
    name: 'Mauritania',
    nationality: 'Mauritanian',
  },
  {
    numCode: '480',
    shortCode: 'MU',
    fullCode: 'MUS',
    name: 'Mauritius',
    nationality: 'Mauritian',
  },
  {
    numCode: '175',
    shortCode: 'YT',
    fullCode: 'MYT',
    name: 'Mayotte',
    nationality: 'Mahoran',
  },
  {
    numCode: '484',
    shortCode: 'MX',
    fullCode: 'MEX',
    name: 'Mexico',
    nationality: 'Mexican',
  },
  {
    numCode: '583',
    shortCode: 'FM',
    fullCode: 'FSM',
    name: 'Micronesia (Federated States of)',
    nationality: 'Micronesian',
  },
  {
    numCode: '498',
    shortCode: 'MD',
    fullCode: 'MDA',
    name: 'Moldova (Republic of)',
    nationality: 'Moldovan',
  },
  {
    numCode: '492',
    shortCode: 'MC',
    fullCode: 'MCO',
    name: 'Monaco',
    nationality: 'Mon\u00e9gasque, Monacan',
  },
  {
    numCode: '496',
    shortCode: 'MN',
    fullCode: 'MNG',
    name: 'Mongolia',
    nationality: 'Mongolian',
  },
  {
    numCode: '499',
    shortCode: 'ME',
    fullCode: 'MNE',
    name: 'Montenegro',
    nationality: 'Montenegrin',
  },
  {
    numCode: '500',
    shortCode: 'MS',
    fullCode: 'MSR',
    name: 'Montserrat',
    nationality: 'Montserratian',
  },
  {
    numCode: '504',
    shortCode: 'MA',
    fullCode: 'MAR',
    name: 'Morocco',
    nationality: 'Moroccan',
  },
  {
    numCode: '508',
    shortCode: 'MZ',
    fullCode: 'MOZ',
    name: 'Mozambique',
    nationality: 'Mozambican',
  },
  {
    numCode: '104',
    shortCode: 'MM',
    fullCode: 'MMR',
    name: 'Myanmar',
    nationality: 'Burmese',
  },
  {
    numCode: '516',
    shortCode: 'NA',
    fullCode: 'NAM',
    name: 'Namibia',
    nationality: 'Namibian',
  },
  {
    numCode: '520',
    shortCode: 'NR',
    fullCode: 'NRU',
    name: 'Nauru',
    nationality: 'Nauruan',
  },
  {
    numCode: '524',
    shortCode: 'NP',
    fullCode: 'NPL',
    name: 'Nepal',
    nationality: 'Nepali, Nepalese',
  },
  {
    numCode: '528',
    shortCode: 'NL',
    fullCode: 'NLD',
    name: 'Netherlands',
    nationality: 'Dutch, Netherlandic',
  },
  {
    numCode: '540',
    shortCode: 'NC',
    fullCode: 'NCL',
    name: 'New Caledonia',
    nationality: 'New Caledonian',
  },
  {
    numCode: '554',
    shortCode: 'NZ',
    fullCode: 'NZL',
    name: 'New Zealand',
    nationality: 'New Zealand, NZ',
  },
  {
    numCode: '558',
    shortCode: 'NI',
    fullCode: 'NIC',
    name: 'Nicaragua',
    nationality: 'Nicaraguan',
  },
  {
    numCode: '562',
    shortCode: 'NE',
    fullCode: 'NER',
    name: 'Niger',
    nationality: 'Nigerien',
  },
  {
    numCode: '566',
    shortCode: 'NG',
    fullCode: 'NGA',
    name: 'Nigeria',
    nationality: 'Nigerian',
  },
  {
    numCode: '570',
    shortCode: 'NU',
    fullCode: 'NIU',
    name: 'Niue',
    nationality: 'Niuean',
  },
  {
    numCode: '574',
    shortCode: 'NF',
    fullCode: 'NFK',
    name: 'Norfolk Island',
    nationality: 'Norfolk Island',
  },
  {
    numCode: '580',
    shortCode: 'MP',
    fullCode: 'MNP',
    name: 'Northern Mariana Islands',
    nationality: 'Northern Marianan',
  },
  {
    numCode: '578',
    shortCode: 'NO',
    fullCode: 'NOR',
    name: 'Norway',
    nationality: 'Norwegian',
  },
  {
    numCode: '512',
    shortCode: 'OM',
    fullCode: 'OMN',
    name: 'Oman',
    nationality: 'Omani',
  },
  {
    numCode: '586',
    shortCode: 'PK',
    fullCode: 'PAK',
    name: 'Pakistan',
    nationality: 'Pakistani',
  },
  {
    numCode: '585',
    shortCode: 'PW',
    fullCode: 'PLW',
    name: 'Palau',
    nationality: 'Palauan',
  },
  {
    numCode: '275',
    shortCode: 'PS',
    fullCode: 'PSE',
    name: 'Palestine, State of',
    nationality: 'Palestinian',
  },
  {
    numCode: '591',
    shortCode: 'PA',
    fullCode: 'PAN',
    name: 'Panama',
    nationality: 'Panamanian',
  },
  {
    numCode: '598',
    shortCode: 'PG',
    fullCode: 'PNG',
    name: 'Papua New Guinea',
    nationality: 'Papua New Guinean, Papuan',
  },
  {
    numCode: '600',
    shortCode: 'PY',
    fullCode: 'PRY',
    name: 'Paraguay',
    nationality: 'Paraguayan',
  },
  {
    numCode: '604',
    shortCode: 'PE',
    fullCode: 'PER',
    name: 'Peru',
    nationality: 'Peruvian',
  },
  {
    numCode: '608',
    shortCode: 'PH',
    fullCode: 'PHL',
    name: 'Philippines',
    nationality: 'Philippine, Filipino',
  },
  {
    numCode: '612',
    shortCode: 'PN',
    fullCode: 'PCN',
    name: 'Pitcairn',
    nationality: 'Pitcairn Island',
  },
  {
    numCode: '616',
    shortCode: 'PL',
    fullCode: 'POL',
    name: 'Poland',
    nationality: 'Polish',
  },
  {
    numCode: '620',
    shortCode: 'PT',
    fullCode: 'PRT',
    name: 'Portugal',
    nationality: 'Portuguese',
  },
  {
    numCode: '630',
    shortCode: 'PR',
    fullCode: 'PRI',
    name: 'Puerto Rico',
    nationality: 'Puerto Rican',
  },
  {
    numCode: '634',
    shortCode: 'QA',
    fullCode: 'QAT',
    name: 'Qatar',
    nationality: 'Qatari',
  },
  {
    numCode: '638',
    shortCode: 'RE',
    fullCode: 'REU',
    name: 'R\u00e9union',
    nationality: 'R\u00e9unionese, R\u00e9unionnais',
  },
  {
    numCode: '642',
    shortCode: 'RO',
    fullCode: 'ROU',
    name: 'Romania',
    nationality: 'Romanian',
  },
  {
    numCode: '643',
    shortCode: 'RU',
    fullCode: 'RUS',
    name: 'Russian Federation',
    nationality: 'Russian',
  },
  {
    numCode: '646',
    shortCode: 'RW',
    fullCode: 'RWA',
    name: 'Rwanda',
    nationality: 'Rwandan',
  },
  {
    numCode: '652',
    shortCode: 'BL',
    fullCode: 'BLM',
    name: 'Saint Barth\u00e9lemy',
    nationality: 'Barth\u00e9lemois',
  },
  {
    numCode: '654',
    shortCode: 'SH',
    fullCode: 'SHN',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    nationality: 'Saint Helenian',
  },
  {
    numCode: '659',
    shortCode: 'KN',
    fullCode: 'KNA',
    name: 'Saint Kitts and Nevis',
    nationality: 'Kittitian or Nevisian',
  },
  {
    numCode: '662',
    shortCode: 'LC',
    fullCode: 'LCA',
    name: 'Saint Lucia',
    nationality: 'Saint Lucian',
  },
  {
    numCode: '663',
    shortCode: 'MF',
    fullCode: 'MAF',
    name: 'Saint Martin (French part)',
    nationality: 'Saint-Martinoise',
  },
  {
    numCode: '666',
    shortCode: 'PM',
    fullCode: 'SPM',
    name: 'Saint Pierre and Miquelon',
    nationality: 'Saint-Pierrais or Miquelonnais',
  },
  {
    numCode: '670',
    shortCode: 'VC',
    fullCode: 'VCT',
    name: 'Saint Vincent and the Grenadines',
    nationality: 'Saint Vincentian, Vincentian',
  },
  {
    numCode: '882',
    shortCode: 'WS',
    fullCode: 'WSM',
    name: 'Samoa',
    nationality: 'Samoan',
  },
  {
    numCode: '674',
    shortCode: 'SM',
    fullCode: 'SMR',
    name: 'San Marino',
    nationality: 'Sammarinese',
  },
  {
    numCode: '678',
    shortCode: 'ST',
    fullCode: 'STP',
    name: 'Sao Tome and Principe',
    nationality: 'S\u00e3o Tom\u00e9an',
  },
  {
    numCode: '682',
    shortCode: 'SA',
    fullCode: 'SAU',
    name: 'Saudi Arabia',
    nationality: 'Saudi, Saudi Arabian',
  },
  {
    numCode: '686',
    shortCode: 'SN',
    fullCode: 'SEN',
    name: 'Senegal',
    nationality: 'Senegalese',
  },
  {
    numCode: '688',
    shortCode: 'RS',
    fullCode: 'SRB',
    name: 'Serbia',
    nationality: 'Serbian',
  },
  {
    numCode: '690',
    shortCode: 'SC',
    fullCode: 'SYC',
    name: 'Seychelles',
    nationality: 'Seychellois',
  },
  {
    numCode: '694',
    shortCode: 'SL',
    fullCode: 'SLE',
    name: 'Sierra Leone',
    nationality: 'Sierra Leonean',
  },
  {
    numCode: '702',
    shortCode: 'SG',
    fullCode: 'SGP',
    name: 'Singapore',
    nationality: 'Singaporean',
  },
  {
    numCode: '534',
    shortCode: 'SX',
    fullCode: 'SXM',
    name: 'Sint Maarten (Dutch part)',
    nationality: 'Sint Maarten',
  },
  {
    numCode: '703',
    shortCode: 'SK',
    fullCode: 'SVK',
    name: 'Slovakia',
    nationality: 'Slovak',
  },
  {
    numCode: '705',
    shortCode: 'SI',
    fullCode: 'SVN',
    name: 'Slovenia',
    nationality: 'Slovenian, Slovene',
  },
  {
    numCode: '90',
    shortCode: 'SB',
    fullCode: 'SLB',
    name: 'Solomon Islands',
    nationality: 'Solomon Island',
  },
  {
    numCode: '706',
    shortCode: 'SO',
    fullCode: 'SOM',
    name: 'Somalia',
    nationality: 'Somali, Somalian',
  },
  {
    numCode: '710',
    shortCode: 'ZA',
    fullCode: 'ZAF',
    name: 'South Africa',
    nationality: 'South African',
  },
  {
    numCode: '239',
    shortCode: 'GS',
    fullCode: 'SGS',
    name: 'South Georgia and the South Sandwich Islands',
    nationality: 'South Georgia or South Sandwich Islands',
  },
  {
    numCode: '728',
    shortCode: 'SS',
    fullCode: 'SSD',
    name: 'South Sudan',
    nationality: 'South Sudanese',
  },
  {
    numCode: '724',
    shortCode: 'ES',
    fullCode: 'ESP',
    name: 'Spain',
    nationality: 'Spanish',
  },
  {
    numCode: '144',
    shortCode: 'LK',
    fullCode: 'LKA',
    name: 'Sri Lanka',
    nationality: 'Sri Lankan',
  },
  {
    numCode: '729',
    shortCode: 'SD',
    fullCode: 'SDN',
    name: 'Sudan',
    nationality: 'Sudanese',
  },
  {
    numCode: '740',
    shortCode: 'SR',
    fullCode: 'SUR',
    name: 'Suriname',
    nationality: 'Surinamese',
  },
  {
    numCode: '744',
    shortCode: 'SJ',
    fullCode: 'SJM',
    name: 'Svalbard and Jan Mayen',
    nationality: 'Svalbard',
  },
  {
    numCode: '748',
    shortCode: 'SZ',
    fullCode: 'SWZ',
    name: 'Swaziland',
    nationality: 'Swazi',
  },
  {
    numCode: '752',
    shortCode: 'SE',
    fullCode: 'SWE',
    name: 'Sweden',
    nationality: 'Swedish',
  },
  {
    numCode: '756',
    shortCode: 'CH',
    fullCode: 'CHE',
    name: 'Switzerland',
    nationality: 'Swiss',
  },
  {
    numCode: '760',
    shortCode: 'SY',
    fullCode: 'SYR',
    name: 'Syrian Arab Republic',
    nationality: 'Syrian',
  },
  {
    numCode: '158',
    shortCode: 'TW',
    fullCode: 'TWN',
    name: 'Taiwan, Province of China',
    nationality: 'Chinese, Taiwanese',
  },
  {
    numCode: '762',
    shortCode: 'TJ',
    fullCode: 'TJK',
    name: 'Tajikistan',
    nationality: 'Tajikistani',
  },
  {
    numCode: '834',
    shortCode: 'TZ',
    fullCode: 'TZA',
    name: 'Tanzania, United Republic of',
    nationality: 'Tanzanian',
  },
  {
    numCode: '764',
    shortCode: 'TH',
    fullCode: 'THA',
    name: 'Thailand',
    nationality: 'Thai',
  },
  {
    numCode: '626',
    shortCode: 'TL',
    fullCode: 'TLS',
    name: 'Timor-Leste',
    nationality: 'Timorese',
  },
  {
    numCode: '768',
    shortCode: 'TG',
    fullCode: 'TGO',
    name: 'Togo',
    nationality: 'Togolese',
  },
  {
    numCode: '772',
    shortCode: 'TK',
    fullCode: 'TKL',
    name: 'Tokelau',
    nationality: 'Tokelauan',
  },
  {
    numCode: '776',
    shortCode: 'TO',
    fullCode: 'TON',
    name: 'Tonga',
    nationality: 'Tongan',
  },
  {
    numCode: '780',
    shortCode: 'TT',
    fullCode: 'TTO',
    name: 'Trinidad and Tobago',
    nationality: 'Trinidadian or Tobagonian',
  },
  {
    numCode: '788',
    shortCode: 'TN',
    fullCode: 'TUN',
    name: 'Tunisia',
    nationality: 'Tunisian',
  },
  {
    numCode: '792',
    shortCode: 'TR',
    fullCode: 'TUR',
    name: 'Turkey',
    nationality: 'Turkish',
  },
  {
    numCode: '795',
    shortCode: 'TM',
    fullCode: 'TKM',
    name: 'Turkmenistan',
    nationality: 'Turkmen',
  },
  {
    numCode: '796',
    shortCode: 'TC',
    fullCode: 'TCA',
    name: 'Turks and Caicos Islands',
    nationality: 'Turks and Caicos Island',
  },
  {
    numCode: '798',
    shortCode: 'TV',
    fullCode: 'TUV',
    name: 'Tuvalu',
    nationality: 'Tuvaluan',
  },
  {
    numCode: '800',
    shortCode: 'UG',
    fullCode: 'UGA',
    name: 'Uganda',
    nationality: 'Ugandan',
  },
  {
    numCode: '804',
    shortCode: 'UA',
    fullCode: 'UKR',
    name: 'Ukraine',
    nationality: 'Ukrainian',
  },
  {
    numCode: '784',
    shortCode: 'AE',
    fullCode: 'ARE',
    name: 'United Arab Emirates',
    nationality: 'Emirati, Emirian, Emiri',
  },
  {
    numCode: '826',
    shortCode: 'GB',
    fullCode: 'GBR',
    name: 'United Kingdom of Great Britain and Northern Ireland',
    nationality: 'British, UK',
  },
  {
    numCode: '581',
    shortCode: 'UM',
    fullCode: 'UMI',
    name: 'United States Minor Outlying Islands',
    nationality: 'American',
  },
  {
    numCode: '840',
    shortCode: 'US',
    fullCode: 'USA',
    name: 'United States of America',
    nationality: 'American',
  },
  {
    numCode: '858',
    shortCode: 'UY',
    fullCode: 'URY',
    name: 'Uruguay',
    nationality: 'Uruguayan',
  },
  {
    numCode: '860',
    shortCode: 'UZ',
    fullCode: 'UZB',
    name: 'Uzbekistan',
    nationality: 'Uzbekistani, Uzbek',
  },
  {
    numCode: '548',
    shortCode: 'VU',
    fullCode: 'VUT',
    name: 'Vanuatu',
    nationality: 'Ni-Vanuatu, Vanuatuan',
  },
  {
    numCode: '862',
    shortCode: 'VE',
    fullCode: 'VEN',
    name: 'Venezuela (Bolivarian Republic of)',
    nationality: 'Venezuelan',
  },
  {
    numCode: '704',
    shortCode: 'VN',
    fullCode: 'VNM',
    name: 'Vietnam',
    nationality: 'Vietnamese',
  },
  {
    numCode: '92',
    shortCode: 'VG',
    fullCode: 'VGB',
    name: 'Virgin Islands (British)',
    nationality: 'British Virgin Island',
  },
  {
    numCode: '850',
    shortCode: 'VI',
    fullCode: 'VIR',
    name: 'Virgin Islands (U.S.)',
    nationality: 'U.S. Virgin Island',
  },
  {
    numCode: '876',
    shortCode: 'WF',
    fullCode: 'WLF',
    name: 'Wallis and Futuna',
    nationality: 'Wallis and Futuna, Wallisian or Futunan',
  },
  {
    numCode: '732',
    shortCode: 'EH',
    fullCode: 'ESH',
    name: 'Western Sahara',
    nationality: 'Sahrawi, Sahrawian, Sahraouian',
  },
  {
    numCode: '887',
    shortCode: 'YE',
    fullCode: 'YEM',
    name: 'Yemen',
    nationality: 'Yemeni',
  },
  {
    numCode: '894',
    shortCode: 'ZM',
    fullCode: 'ZMB',
    name: 'Zambia',
    nationality: 'Zambian',
  },
  {
    numCode: '716',
    shortCode: 'ZW',
    fullCode: 'ZWE',
    name: 'Zimbabwe',
    nationality: 'Zimbabwean',
  },
];
