export const Routes = {
  SignIn: '/sign-in',
  ResetPassword: '/reset',
  ConfirmEmailChange: '/confirm-email-change/:token',
  Home: '/',
  AboutUs: '/about-us',
  GetInTouch: '/get-in-touch',
  Plans: '/plans',
  PartnerProgram: '/partner-program',
  Insights: '/insights',
  Solutions: {
    Root: '/solutions',
    Overview: '/solutions/overview', // ✅ FIXED - Prefixed with "/solutions/"
    Employee: '/solutions/employee',
    Payroll: '/solutions/payroll',
    Company: '/solutions/company',
    Business: '/solutions/business',
    Mobile: '/solutions/mobile',
    IvySupport: '/solutions/ivy-support',
  },
  DemoRequest: '/demo-request',
  ServiceRequest: '/service-request',
  Article: '/insights/:title',
  Careers: '/careers',
  JobDescription: '/job-description/:id',
  Security: '/security',
};
